import Head from 'next/head';
import Converter from '@components/converter';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid place-items-center min-h-screen">
        <Converter />
      </main>
    </>
  );
}
